### ISSUE TITLE
Add Metadata configuring page 

### ISSUE THREAD

**Issue by donhinkelman** [ponlawat-w/moodle-block_hubcourseinfo#2]
Plugin admins like Martin or I, may need to add new metadata, or revise old metadata.  Such as "physical postal address" as an optional field.

**Comment by ponlawat-w** [comment]
I have added the feature of customisable metadata fields.
The latest code is now merged into `master` branch.

To setup the custom fields, the settings are located in site administrator page » block settings of the `hubcourseinfo` block (shown in the picture below).

![image](https://user-images.githubusercontent.com/15243484/115106091-fa639480-9f8c-11eb-8ffe-50634d660bfd.jpeg)

**Comment by donhinkelman** [comment]
This looks good. One question: What happens when you lower the Maximum Version Amount?  Does one version get automatically deleted?  I would expect a pop up window would show all the versions stored, and ask "Which version do you wish to delete?". It is possible that we would want to reduce versions if storage space on the server became full.

**Comment by donhinkelman** [comment]
Also, simpler English would be "Maximum number of versions stored for one course". Default I think should be 2.`

**Comment by ponlawat-w** [comment]
> This looks good. One question: What happens when you lower the Maximum Version Amount?  Does one version get automatically deleted?  I would expect a pop up window would show all the versions stored, and ask "Which version do you wish to delete?". It is possible that we would want to reduce versions if storage space on the server became full.

For now if we reduce the maximum version number in this version there will be no changes to the existing versions in the website, the only affect will be that the authors are not be able to add more new versions.

**Comment by ponlawat-w** [comment]
> Also, simpler English would be "Maximum number of versions stored for one course". Default I think should be 2.`

We can make this to be another issue.
