### ISSUE TITLE
Download metadata into a CSV file

### ISSUE THREAD

**Issue by donhinkelman** [ponlawat-w/moodle-block_hubcourseinfo#3]
Download metadata of one course into a CSV file.  Including all metadata plus dates such as first uploaded, and last update, for example. I don't think it is possible to download all metadata of all courses into one file, but if it is easy to do, add that function too. This is a lower priority fix.

**Comment by ponlawat-w** [comment]
Hi Don,

The export to CSV feature has been implemented.
The button to export for individual course can be found in the manage page of each course next to edit metadata button:
![image](https://user-images.githubusercontent.com/15243484/115834515-83704500-a43f-11eb-9564-f42e8df39567.jpeg)

For site administrators, they can export the CSV of all courses in the website by going to plugin settings in Site Administration (the same place where we can configure the subjects, custom metadata), a button called "export metadata of all courses" is located there:
![image](https://user-images.githubusercontent.com/15243484/115834673-adc20280-a43f-11eb-9b12-56dd65548364.jpeg)
