### ISSUE TITLE
Add feature to Rebuild Course Backup

### ISSUE THREAD

**Issue by donhinkelman** [ponlawat-w/moodle-block_hubcourseinfo#4]
Add a "rebuild course backup" feature. Next to or near the "reset course" (which returns the backup file to the original), we need a button which replaces the current backup with a backup of the displayed course on the showcase, this includes any discussion forum by course authors. We will use this a lot as an author or a group of authors revise and improve their courses. **This feature is the highest priority.**

**Comment by ponlawat-w** [comment]
OK, I am working on this issue.

**Comment by ponlawat-w** [comment]
Feature added and ready to test.
The [upload block repository](https://github.com/ponlawat-w/moodle-block_hubcourseupload) is also updated from this change.
